### PR TITLE
Work on styles, code refactor, add boulder data to chart, and pie chart tab.

### PR DESCRIPTION
**Pull request by dgendill**
This adds some styles for the tabs. I've moved the javascript code to es6 and added a webpack config file. 
Dev process should be the same as before though - just run `npm start` and it will compile automatically. If you have an existing branch pull in the latest changes and run `npm install`.  I also added the data we got from the boulder permits, and a pie chart showing Fort Collin's energy ratios from 2015.

### CODE REVIEW

**Comment by abettermap** [comment]
Pie chart looks great! And webpack worked fine. 

Do you think we need to track *code/dist*? It's ~2MB worth of generated code, so the diff will likely always be pretty heavy. We aren't tracking the generated CSS, so can we follow suit with the JS? It will still publish correctly with `npm run publish-gh-pages`.

If that's cool, I'd say `.gitignore` it, push, and merge.

**Comment by dgendill** [comment]
Good idea, I've remove the files in the dist folder.

**Comment by dgendill** [comment]
I'll look at your branch and integrate your changes into what I have.

**Comment by dgendill** [comment]
@abettermap  The other night, I saw you had some new styles for the tabs and charts.  Are those on your branch? I looked in the scss folder and it looks like they might be missing. I went ahead and just integrated your html, mustache, and tab changes and kept the styles we previously had. I also hooked up the callback stuff so each tab can specify it's own content externally.

**Comment by abettermap** [comment]
I didn't push those changes initially because they were pretty work-in-progress. If you want them they are in the commit I pushed just now: https://github.com/CodeForFoco/solar-scorecard/commit/481f0f685836a87eb3fa6547647ec87a7305f349. Otherwise I think we can just merge your PR but leave #25 open until one of us has time to make it nice and pretty.

Nice work on the Mustache integration, everything worked fine when I pulled in your changes, although I did get an error briefly about `Stairstep Chart` not being defined but it went away as soon as I navigated directly to *index.html*, and then after that the usual web root of */code/* without the *index.html* worked fine.

**Comment by dgendill** [comment]
Sounds good, thanks. I'll let you carry on with the styling you were working on, and if I start on something new I'll let you know. I might start on #27 this week.

**Pull request merged**
