### PR TITLE
Automate dev process

### PR DESCRIPTION
**Pull request by abettermap**
Use `npm` to make SCSS and TS compiling more automatic.

### CODE REVIEW

**Comment by abettermap** [comment]
@dgendill 

Probably overkill for this project but I wanted some Node practice 😉 

Try this when you get a chance:

```
npm install
npm start
```

Let me know if anything catches on fire.

**Comment by abettermap** [comment]
Also not sure I did things in the right order because I wanted to include your *package.json* update so I started a branch from there and now it looks like there are a lot of commits unrelated to this PR:
screen shot 2017-06-25 at 7 04 53 pm

**Comment by dgendill** [comment]
Nice!  Install and build work for me, and it did the compilation afterwords.  The only thing I ran into is `npm install` on it's own didn't install the typescript and browsersync devDependencies. I think that might be specific to my system because I have the NODE_ENV environment variable set to "production".  So I had to run `NODE_ENV=development; npm install` instead.  I don't think npm has a build in way to distinguish between development postinstall and production postinstall, so maybe we should move the devDependencies to regular dependencies just to simplify things - At least right now, we probably don't need to distinguish between the two environments.

**Comment by abettermap** [comment]
Done and done: #17

**Pull request merged**
